from sqlalchemy import Column, Integer, String, ForeignKey, Text
from .database import Base

class Paciente(Base):
    __tablename__ = "pacientes"
    id = Column(Integer, primary_key=True, index=True)
    nombre = Column(String)
    apellido = Column(String)
    ci = Column(String, unique=True)
    codigo_paciente = Column(String)

class DeclaracionJurada(Base):
    __tablename__ = "declaraciones_p1"
    id = Column(Integer, primary_key=True, index=True)
    paciente_id = Column(Integer, ForeignKey("pacientes.id"))
    edad = Column(String)
    sexo = Column(String)
    fecha_nacimiento = Column(String)
    lugar_nacimiento = Column(String)
    domicilio = Column(String)
    n_casa = Column(String, default="")
    zona_barrio = Column(String, default="")
    ciudad = Column(String)
    pais = Column(String)
    telefono = Column(String, default="")
    estado_civil = Column(String)
    profesion_oficio = Column(String, default="")

class AntecedentesP2(Base):
    __tablename__ = "declaraciones_p2"
    id = Column(Integer, primary_key=True, index=True)
    paciente_id = Column(Integer, ForeignKey("pacientes.id"))
    vista = Column(String, default="NO")
    vista_obs = Column(Text, default="")
    auditivo = Column(String, default="NO")
    auditivo_obs = Column(Text, default="")
    respiratorio = Column(String, default="NO")
    respiratorio_obs = Column(Text, default="")
    cardiovasculares = Column(String, default="NO")
    cardiovasculares_obs = Column(Text, default="")
    digestivos = Column(String, default="NO")
    digestivos_obs = Column(Text, default="")
    sangre = Column(String, default="NO")
    sangre_obs = Column(Text, default="")
    genitourinario = Column(String, default="NO")
    genitourinario_obs = Column(Text, default="")
    sistema_nervioso = Column(String, default="NO")
    sistema_nervioso_obs = Column(Text, default="")
    psiquiatricos = Column(String, default="NO")
    psiquiatricos_obs = Column(Text, default="")
    osteomusculares = Column(String, default="NO")
    osteomusculares_obs = Column(Text, default="")
    endocrino = Column(String, default="NO")
    endocrino_obs = Column(Text, default="")
    alergias = Column(String, default="NO")
    alergias_obs = Column(Text, default="")
    cirugias = Column(String, default="NO")
    cirugias_obs = Column(Text, default="")
    accidentes_trabajo = Column(String, default="NO")
    accidentes_trabajo_obs = Column(Text, default="")
    accidentes_pers = Column(String, default="NO")
    accidentes_pers_obs = Column(Text, default="")
    medicamentos = Column(String, default="NO")
    medicamentos_obs = Column(Text, default="")
    infecciosas = Column(String, default="NO")
    infecciosas_obs = Column(Text, default="")
    ap_urinario = Column(String, default="NO")
    ap_urinario_obs = Column(Text, default="")
    linfatico = Column(String, default="NO")
    linfatico_obs = Column(Text, default="")
    reumatologicos = Column(String, default="NO")
    reumatologicos_obs = Column(Text, default="")
    otros = Column(String, default="NO")
    otros_obs = Column(Text, default="")
    generales = Column(String, default="NO")
    generales_obs = Column(Text, default="")

class HabitosRiesgosP3(Base):
    __tablename__ = "declaraciones_p3"
    id = Column(Integer, primary_key=True, index=True)
    paciente_id = Column(Integer, ForeignKey("pacientes.id"))
    fuma = Column(String, default="NO")
    bebe_alcohol = Column(String, default="NO")
    deporte = Column(String, default="NO")
    observaciones = Column(Text, default="")
